# Generated by Django 4.0.5 on 2022-06-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(blank=True, choices=[('Petrenko', 'Петренко'), ('Shevchenko', 'Шевченко')], max_length=100, null=True, verbose_name='Surname'),
        ),
    ]
